import { StyleSheet, Dimensions, Platform } from "react-native";
const {height, width} = Dimensions.get('screen');


export const shipmentItemStyles = StyleSheet.create({
    container: {
     marginVertical:3
    },
    topWrapper:{
        flexDirection:"row",
        justifyContent:"space-between",
        paddingVertical:10,
        alignItems:"center",
        backgroundColor:"#F4F2F8",
        paddingHorizontal:10
    },
    bottomWrapper:{
        borderStyle:"dotted",
        paddingVertical:10,
        backgroundColor:"#F4F2F8",
        paddingHorizontal:10,
        borderWidth:5,
        borderColor:"#fff"
    },
    checkbox:{
      borderColor:"#D0D5DD",
      width:22,
      height:22,
      borderRadius:5
    },
    box:{
        width:32,
        height:32,
        marginHorizontal:4
    },
    txt1:{
     fontSize:13,
     fontFamily:"SpfRegularText",
     color:"#3F395C"
    },
    txt2:{
        fontSize:18,
        fontFamily:"SpfSemiBoldText",
        color:"#000"
       },
       txt3:{
        fontSize:13,
        fontFamily:"SpfRegularText",
        color:"#757281"
       },
       txt4:{
        fontSize:11,
        fontFamily:"SpfRegularText",
        color:"#2F50C1"
       },
       txt5:{
        fontSize:16,
        fontFamily:"SpfRegularText",
        color:"#000"
       },

       txt6:{
        fontSize:13,
        fontFamily:"SpfLightText",
        color:"#58536E"
       },
    callBtn:{
     backgroundColor:"#6E91EC",
     paddingVertical:7,
     paddingHorizontal:15,
     flexDirection:"row",
     alignItems:"center",
     borderRadius:10,
    },
    callBtnTxt:{
       color:"#fff",
       fontSize:16,
       fontFamily:"SpfRegularText",
  
       },
    whatsappBtn:{
        marginLeft:20,
        backgroundColor:"#25D366",
        paddingVertical:7,
        paddingHorizontal:15,
        flexDirection:"row",
        alignItems:"center",
        borderRadius:10,
    },
    whatsappBtnText:{
        color:"#fff",
        fontSize:16,
        fontFamily:"SpfRegularText",
    },
       statusBtn:{
        backgroundColor:"#D9E6FD",
        borderRadius:4,
        paddingVertical:5,
        paddingHorizontal:5,
        width:80,
        marginRight:4
       },
       statusBtnTxt:{
        fontSize:11,
        fontFamily:"SpfMediumText",
        color:"#2F50C1",
        textAlign:"center"
       },
    openBtn:{
        borderRadius:50,
         padding:6,
         backgroundColor:"#fff"
    },
    flexBetween:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center"
    },
    flexEnd:{
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center"
    }

});